### ISSUE TITLE
Geen tegel met instellingen gevondern

### ISSUE THREAD

**Issue by MadPatrick** [oepi-loepi/AutoReboot#1]
Hi
Ik heb deze app geïnstalleerd op mijn Toon v2, maar waar kan in instellingen hiervoor vinden

**Comment by oepi-loepi** [comment]
Klopt. AutoReboot heeft geen instellingen om het proggie zo compact mogelijk te houden. Hij laat de toon gewoon op dag 1, 3 en 5 om 03:30 rebooten (ma, wo en vr)

**Comment by MadPatrick** [comment]
Aha. Ok bedankt.
